const EMAIL_USER = process.env.REACT_APP_EMAIL_USER;
const EMAIL_SERVICE = process.env.REACT_APP_EMAIL_SERVICE;
const EMAIL_TEMPLATE = process.env.REACT_APP_EMAIL_TEMPLATE;
  
export {
  EMAIL_USER,
  EMAIL_SERVICE,
  EMAIL_TEMPLATE,
};